[package]
name = "year_2024"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
progress_timer = { git = "https://github.com/ninouGx/progress_timer" }
aoc_utils = { path = "../aoc_utils" }
rayon = "1.10.0"
